gemp-lotr/gemp-lotr-async/src/main/web/deckBuild.html
gemp-lotr/gemp-lotr-async/src/main/web/src/DeckBuilder/deckBuilder.js
gemp-lotr/gemp-lotr-async/src/main/web/src/DeckBuilder/index.css

Small PR to remove all inline stylings from the deckbuilder. No changes made to functionality.
All tested on playtest server.

Pull Inline Stylings from deckbuild

---

gemp-lotr/gemp-lotr-cards/src/main/resources/cards/unofficial/hobbit/set32/set32-fp.hjson

Should be classified as a Ring

Fix for The Hobit Draft Game's "Narya"

---

gemp-lotr/gemp-lotr-async/src/main/web/css/gemp-001/autozoom.css
gemp-lotr/gemp-lotr-async/src/main/web/css/gemp-001/deckBuild.css
gemp-lotr/gemp-lotr-async/src/main/web/css/gemp-001/game.css
gemp-lotr/gemp-lotr-async/src/main/web/deckBuild.html
gemp-lotr/gemp-lotr-async/src/main/web/game.html
gemp-lotr/gemp-lotr-async/src/main/web/js/gemp-022/autoZoomHandler.js
gemp-lotr/gemp-lotr-async/src/main/web/js/gemp-022/deckBuildingUi.js
gemp-lotr/gemp-lotr-async/src/main/web/js/gemp-022/gameAnimations.js
gemp-lotr/gemp-lotr-async/src/main/web/js/gemp-022/gameUi.js
gemp-lotr/gemp-lotr-async/src/main/web/js/gemp-022/jCards.js

Adds auto-zoom for the game and deckbuilder screens.  This is a way to quickly see all the cards on the field or in the deckbuilder without needing to click on each one.  Also adds a toggle button for disabling the feature on each of those screens.

Adding auto-zoom

---

gemp-lotr/gemp-lotr-cards/src/main/resources/cards/unofficial/pc/setV02/setv02-Gandalf-playtest.hjson
gemp-lotr/gemp-lotr-server/src/test/java/com/gempukku/lotro/cards/unofficial/pc/vsets/set_v02/Card_V2_012_Tests.java

This is not yet ready to merge but I do seem to be stuck on progress for this card and would be happy for a second set of eyes to take a look. 
Basing the hjson off of similar cards, I think it's close to correct but have been having a hard time getting tests to work as I'd expect. 
If I filter to just possession it seems to correctly identify all possessions in my discard as optional targets but filtering to `pipe(weed)` or `pipe(weed),possession` results in no selectable cards. In all cases, I've failed to get the tests to actually put the selected cards back in the draw deck. 
I'm happy to take advise or to jump into a pairing call to look over some of the options that might make this work as expected.

Initial attempt at jetsam

---

gemp-lotr/gemp-lotr-async/src/main/web/hall.html
gemp-lotr/gemp-lotr-async/src/main/web/includes/admin/leagueAdmin.html
gemp-lotr/gemp-lotr-server/src/main/java/com/gempukku/lotro/hall/GameTimer.java

A step in the right direction towards game timers that reflect the reasons players are choosing them. These should be reviewed in the future once we've got some sort of metric to compare the times against -- % of games that run out of time, for example, or some analysis on predicting a rage quit vs a temporary disconnect vs a hard turn to think through. I suspect that, with the possible exception of the default decision timer, these times are still quite generous.

Adjusting Game Timers

---

gemp-lotr/gemp-lotr-cards/src/main/resources/cards/official/set13/set13-Orc.hjson

Always threatening is removing 1 token instead of two when the token removal option is chosen, this PR adds `count: 2` to that option. 
I believe this fixes #421 and #453

Fix: Number of culture tokens for Always Threatening

---

gemp-lotr/gemp-lotr-cards/src/main/resources/cards/official/set10/set10-Gandalf.hjson

This PR stops Brooding on Tomorrow from working during the fellowship phase.
I believe this PR fixes #451 and #408

Fix: Brooding on tomorrow working in Fellowship Phase

---

gemp-lotr/gemp-lotr-cards/src/main/resources/cards/official/set11/set11-Uruk-hai.hjson

This PR should convince Force of Uruk-Hai to only have it's ability at battlegrounds.
I believe this fixes #444

Fix: Force of Uruk-hai not respecting battleground requirement

---

gemp-lotr/gemp-lotr-cards/src/main/resources/cards/official/set03/set03-Sauron.hjson

This PR should make Decipher's Hand of Sauron's discard random. 
I believe this fixes #442

Fix: And of Sauron (D) not being random

---

gemp-lotr/gemp-lotr-cards/src/main/resources/cards/official/set06/set06-Gandalf.hjson

This same issue was tackled for Skin Bark and Host of Fanghorn in [this commit](https://github.com/PlayersCouncil/gemp-lotr/commit/478c907dc72b7a46fa999e4ee8c5e8259f11abe5) and for Quickbeam in [this one](https://github.com/PlayersCouncil/gemp-lotr/commit/87cb10bede898a4cdb5556a43c618a6419ead868) but was missed for the biggest boy. 
I believe this fixes #400 and #433

Fix: Ent Hoard not taking bloom of health modifiers into account

---

gemp-lotr/gemp-lotr-cards/src/main/resources/cards/official/set07/set07-Gandalf.hjson

Gandalf's Staff, Focus of power was triggering off of threat, not twilight, token count. 
I believe this fixes #455

Fix: Focus of Power being into the wrong token

---

gemp-lotr/gemp-lotr-logic/src/main/java/com/gempukku/lotro/cards/build/field/effect/filter/FilterFactory.java

@ketura please triple-check me on this one, I am no Java dev so I'm relying on a bunch of Googled documentation to understand how this works.
The `highestStrength` has, what appears to be, a duplication error having been copied from the `lowestStrength` filter (this is conjecture but I believe that's the order of events) where the math check was updated but the initial `int` value was not so this function sets the initial value to the highest integer Java can handle than compares it to each companion's strength choosing the companions strength only if it is higher than Java's maximum integer value of 2147483647. Changing this declaration to be equal to `Integer.MIN_VALUE` should fix the issue (I suspect simply setting it to `0` would also have been sufficient but I'm a stranger here and …

Fix: highestStrength always being 2147483647

---

gemp-lotr/gemp-lotr-cards/src/main/resources/cards/official/set04/set04-Raider.hjson

`Count: 2` was omitted when converted to JSON. 
Fixes #406

Fix: Eastern Emyn Muil not exerting hard enough

---

gemp-lotr/gemp-lotr-cards/src/main/resources/cards/official/set12/set12-Uruk-hai.hjson

Shingle in the Storm was incorrectly set to be a skirmish action where it's too late to assign a character. 
Fixes #396

Fix: Shingle in the Storm being fashionably late

---

gemp-lotr/gemp-lotr-cards/src/main/resources/cards/unofficial/pc/errata/set01/set01-Shire-errata.hjson

We seem to have removed Sam, Faithful Companion's Samness when we did the most recent PC edit. This PR adds his standard response text back. I did check the other Sams just to be safe but other than the couple in expanded that don't have a take up the one ring clause, it seems Faithful Companion was the only one with the issue. 
Fixes #252

Fix: Faithful companion being a bad Sam

---

gemp-lotr/gemp-lotr-cards/src/main/resources/cards/unofficial/pc/errata/set01/set01-Sauron-errata.hjson

Their numbers must be few (PC Errata) looks like it was modifying the move limit in the wrong direction. 
I believe this PR fixes #448

Fix: Their Numbers Must Be Few sneakily being a FP card

---

gemp-lotr/gemp-lotr-logic/src/main/java/com/gempukku/lotro/cards/build/field/effect/trigger/WinsSkirmish.java

I'm feeling a bit outside of my depth here but while investigating #352 I think I've found a code duplication bug that is causing the problem there. It looks like the block for `memorizeInvolving` was copied and modified for `memorizeLoser` but the final param being passed into `actionContext.setCardMemory` was not updated resulting in the filter always passing `null` as the first parameter into that function. This however is where I'm struggling to tell exactly what that effect will result in, I'm trying to dig into the engine but am thus far failing to find the answer and left unsure if this change (while almost certainly needed) will fix #352 or not.

Update MemorizeLoser filter function

---

gemp-lotr/gemp-lotr-server/src/main/java/com/gempukku/lotro/chat/MarkdownParser.java

Users with an underline in their username currently cannot be ignored

No longer escaping command underlines

---

gemp-lotr/gemp-lotr-cards/src/main/resources/cards/official/set10/set10-Ringwraith.hjson

Lemenya didn't specify other Nazgul for his wounding effect. Fixes #529

Fix: Lemenya TotO self wounding

---

gemp-lotr/gemp-lotr-cards/src/main/resources/cards/official/set07/set07-Dwarven.hjson

Fixes #582 - Preparations was only limiting the exerting character by race, not by type.

Fix: Preparations allowing allies to exert

---

gemp-lotr/gemp-lotr-async/src/main/java/com/gempukku/lotro/async/handler/CollectionRequestHandler.java
gemp-lotr/gemp-lotr-async/src/main/web/js/gemp-022/hallUi.js
gemp-lotr/gemp-lotr-server/src/main/java/com/gempukku/lotro/chat/ChatRoom.java
gemp-lotr/gemp-lotr-server/src/main/java/com/gempukku/lotro/chat/ChatRoomMediator.java
gemp-lotr/gemp-lotr-server/src/main/java/com/gempukku/lotro/chat/ChatServer.java
gemp-lotr/gemp-lotr-server/src/main/java/com/gempukku/lotro/hall/HallCommunicationChannel.java
gemp-lotr/gemp-lotr-server/src/main/java/com/gempukku/lotro/hall/HallInfoVisitor.java
gemp-lotr/gemp-lotr-server/src/main/java/com/gempukku/lotro/hall/HallServer.java
gemp-lotr/gemp-lotr-server/src/main/java/com/gempukku/lotro/hall/TableHolder.java
gemp-lotr/gemp-lotr-server/src/main/java/com/gempukku/lotro/tournament/BaseTournament.java
gemp-lotr/gemp-lotr-server/src/main/java/com/gempukku/lotro/tournament/ConstructedTournament.java
gemp-lotr/gemp-lotr-server/src/main/java/com/gempukku/lotro/tournament/SealedTournament.java
gemp-lotr/gemp-lotr-server/src/main/java/com/gempukku/lotro/tournament/SoloDraftTournament.java
gemp-lotr/gemp-lotr-server/src/main/java/com/gempukku/lotro/tournament/SoloTableDraftTournament.java
gemp-lotr/gemp-lotr-server/src/main/java/com/gempukku/lotro/tournament/TableDraftTournament.java
gemp-lotr/gemp-lotr-server/src/main/java/com/gempukku/lotro/tournament/Tournament.java
gemp-lotr/gemp-lotr-server/src/main/java/com/gempukku/lotro/tournament/TournamentService.java

- Fixes #621 
- Fixes visibility of 'Active Tournaments' section in hall not being saved to cookie
- Removes ability to late join to 1v1 tournaments (solo draft and sealed)
- Added all running tournaments to 'Playing Tables' section for all players to promote visibility
- Tournaments with no active players (all dropped) finish early without waiting for timer
- Tournaments with no entry, no prizes, no wc id (casual tournaments) can be spectated and chat can be used by spectators
- Added timers for deck-building, deck registration and tournament pairing delay to game hall
This **does not** fix issue #620 as i was unable to reproduce that bug in my local docker. Hopefully the added timer will help with debugging. Can you try that on playtest server? Join table draft, request start as solo …

Draft fix - partial

---

gemp-lotr/gemp-lotr-async/src/main/java/com/gempukku/lotro/async/handler/AdminRequestHandler.java
gemp-lotr/gemp-lotr-async/src/main/java/com/gempukku/lotro/async/handler/TableDraftRequestHandler.java
gemp-lotr/gemp-lotr-async/src/main/web/includes/admin/generalAdmin.html
gemp-lotr/gemp-lotr-server/src/main/java/com/gempukku/lotro/collection/CollectionsManager.java
gemp-lotr/gemp-lotr-server/src/main/java/com/gempukku/lotro/draft3/TableDraftClassic.java
gemp-lotr/gemp-lotr-server/src/main/java/com/gempukku/lotro/hall/TableHolder.java
gemp-lotr/gemp-lotr-server/src/main/java/com/gempukku/lotro/tournament/SealedTournament.java
gemp-lotr/gemp-lotr-server/src/main/java/com/gempukku/lotro/tournament/SoloDraftTournament.java
gemp-lotr/gemp-lotr-server/src/main/java/com/gempukku/lotro/tournament/TournamentService.java

Proper fix of that tournament name spam hotfix -> accepting this PR will allow nice table names again and reduce the number of db queries
- Greatly reduced the number of db queries which ask for live tournaments
- Also reduced the number of collection related queries related to card removal from collection if draft with the same id starts (should not happen often but since i was already thinking about db optimization...)
- Fixed a bug in sealed tournament caused by reducing the number of said queries - quick testing have not revealed any other problems 
This also probably fixes #620 , but i would still suggest accepting also #629 which solves that 100 %

Tournament db optimization

---

gemp-lotr/gemp-lotr-async/src/main/java/com/gempukku/lotro/async/handler/DeckRequestHandler.java
gemp-lotr/gemp-lotr-async/src/main/web/js/gemp-022/communication.js
gemp-lotr/gemp-lotr-async/src/main/web/js/gemp-022/deckBuildingUi.js
gemp-lotr/gemp-lotr-async/src/main/web/js/gemp-022/deckBuildingUi2.js
gemp-lotr/gemp-lotr-server/src/main/java/com/gempukku/lotro/tournament/TournamentService.java

- Resolves #639 
Tested manually with:
- sealed 1v1
- table draft tournament
- solo draft league
- constructed format to ensure it does not break
Also fixed by this: tournament ids do not contain 'queue' anymore (noticed this now since their collection names contained it)

Limited deck validation + tournament ids modification

---

gemp-lotr/gemp-lotr-async/src/main/java/com/gempukku/lotro/async/handler/AdminRequestHandler.java
gemp-lotr/gemp-lotr-async/src/main/web/js/gemp-022/hallUi.js
gemp-lotr/gemp-lotr-server/src/main/java/com/gempukku/lotro/db/DbTournamentDAO.java
gemp-lotr/gemp-lotr-server/src/main/java/com/gempukku/lotro/hall/HallCommunicationChannel.java
gemp-lotr/gemp-lotr-server/src/main/java/com/gempukku/lotro/hall/HallInfoVisitor.java
gemp-lotr/gemp-lotr-server/src/main/java/com/gempukku/lotro/hall/HallServer.java
gemp-lotr/gemp-lotr-server/src/main/java/com/gempukku/lotro/tournament/AbstractTournamentQueue.java
gemp-lotr/gemp-lotr-server/src/main/java/com/gempukku/lotro/tournament/BaseTournament.java
gemp-lotr/gemp-lotr-server/src/main/java/com/gempukku/lotro/tournament/ConstructedTournament.java
gemp-lotr/gemp-lotr-server/src/main/java/com/gempukku/lotro/tournament/ScheduledTournamentQueue.java
gemp-lotr/gemp-lotr-server/src/main/java/com/gempukku/lotro/tournament/Tournament.java
gemp-lotr/gemp-lotr-server/src/main/java/com/gempukku/lotro/tournament/TournamentParams.java
gemp-lotr/gemp-lotr-server/src/main/java/com/gempukku/lotro/tournament/TournamentQueue.java
gemp-lotr/gemp-lotr-server/src/main/java/com/gempukku/lotro/tournament/TournamentService.java

So i have done some refactoring regarding the WC.
There are some assumptions:
1) being a WC tournament is mainly just a visual thing (+ timer and table names) -> a lot of things regarding the WC is being done manually? since i found no way to generate that upper/lower bracket with different formats and so on
2) WC event are always constructed (would need some changes to properly display sealed or draft wc events)
Work that has been done:
- scheduled wc queues are always in the waiting tables area, even if no players have registered yet, to promote visibility
- removed that hack with WC tournament names and done that on server
- fixed bug with admin scheduled queues that didnt start (not enough players joined) popping in hall every 60 secs for 1 sec
- wc is no longer identified by 'wc' in …

WC queues/tournaments refactoring

---

gemp-lotr/gemp-lotr-cards/src/main/resources/cards/official/set03/set03-Gondor.hjson

This PR increase the exertion-cost count of We Must Go Wearily to 2 to match it's text. 
Related to #704

Update We Must Go Wearily to exert twice

---

gemp-lotr/gemp-lotr-async/src/main/web/deckBuild.html
gemp-lotr/gemp-lotr-async/src/main/web/js/gemp-022/deckBuildingUi.js
gemp-lotr/gemp-lotr-async/src/main/web/js/gemp-022/hallUi.js

Only js and html files changed, no server restart needed
1) Default hall format when page loads is fellowship block instead of anything goes - only the format selector drop down is modified, deck selector still shows anything goes decks first.
2) Convert errata button in deck builder is disabled when the page loads - cannot tell how many times i missclicked my decks / library since their 'position' changes (sometimes they are the right-most button, sometimes not, based on if i had just loaded the page or if i have looked at one of the decks already).
If format is switched to Anything Goes (not when the page loads), the convert button is enabled. It is also enabled after page loads if user starts adding cards to empty anything goes deck.

UI Anything Goes js annoyances
